---------------------------------------------------------
-- SCRIPT PARA APAGAR TODAS AS TABELAS
-- (Fato primeiro, depois dimensões, resolvendo dependências)
---------------------------------------------------------

DROP TABLE FATO_ENTREGA;
DROP TABLE DIM_CLIENTE;
DROP TABLE DIM_CENTRO_DISTRIBUICAO;
DROP TABLE DIM_ENTREGADOR;
DROP TABLE DIM_PRODUTO;
DROP TABLE DIM_SUBCATEGORIA;
DROP TABLE DIM_CATEGORIA;
DROP TABLE DIM_LOGRADOURO;
DROP TABLE DIM_BAIRRO;
DROP TABLE DIM_CIDADE;
DROP TABLE DIM_ESTADO;
DROP TABLE DIM_REGIAO;
DROP TABLE DIM_DATA;