-- =========================================================================
-- Tabela: DIM_REGIAO
-- =========================================================================
CREATE TABLE DIM_REGIAO (
    FK_DIM_REGIAO   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOME_REGIAO     VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_DIM_REGIAO PRIMARY KEY (FK_DIM_REGIAO)
);

COMMENT ON TABLE DIM_REGIAO IS
    'Dimensão que armazena informações de macrorregiões (Norte, Nordeste, Centro-Oeste, Sudeste, Sul).';

COMMENT ON COLUMN DIM_REGIAO.FK_DIM_REGIAO IS
    'Chave primária gerada por IDENTITY para a dimensão REGIAO.';

COMMENT ON COLUMN DIM_REGIAO.NOME_REGIAO IS
    'Nome da região geográfica (Norte, Nordeste, etc.).';

-- =========================================================================
-- Tabela: DIM_ESTADO
-- =========================================================================
CREATE TABLE DIM_ESTADO (
    FK_DIM_ESTADO   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    SIGLA_ESTADO    CHAR(2)       NOT NULL,
    NOME_ESTADO     VARCHAR2(50)  NOT NULL,
    GENTILICO       VARCHAR2(50),
    ID_REGIAO       NUMBER        NOT NULL,
    CONSTRAINT PK_DIM_ESTADO PRIMARY KEY (FK_DIM_ESTADO),
    CONSTRAINT FK_ESTADO_REGIAO FOREIGN KEY (ID_REGIAO)
        REFERENCES DIM_REGIAO(FK_DIM_REGIAO)
);

COMMENT ON TABLE DIM_ESTADO IS
    'Dimensão que armazena dados dos Estados (UF), referenciando a região a que pertence.';

COMMENT ON COLUMN DIM_ESTADO.FK_DIM_ESTADO IS
    'Chave primária gerada por IDENTITY para a dimensão ESTADO.';

COMMENT ON COLUMN DIM_ESTADO.SIGLA_ESTADO IS
    'Sigla da unidade federativa (por exemplo, SP, RJ).';

COMMENT ON COLUMN DIM_ESTADO.NOME_ESTADO IS
    'Nome por extenso do Estado (por exemplo, São Paulo, Rio de Janeiro).';

COMMENT ON COLUMN DIM_ESTADO.GENTILICO IS
    'Termo que se refere aos habitantes do estado (ex.: paulista, carioca).';

COMMENT ON COLUMN DIM_ESTADO.ID_REGIAO IS
    'Chave estrangeira para DIM_REGIAO, indicando a região a que o Estado pertence.';

-- =========================================================================
-- Tabela: DIM_CIDADE
-- =========================================================================
CREATE TABLE DIM_CIDADE (
    FK_DIM_CIDADE   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOME_CIDADE     VARCHAR2(100) NOT NULL,
    NR_POPULACAO    NUMBER(10,0),
    CODIGO_IBGE     NUMBER(10,0),
    ALTITUDE        NUMBER(5,0),
    ID_ESTADO       NUMBER        NOT NULL,
    CONSTRAINT PK_DIM_CIDADE PRIMARY KEY (FK_DIM_CIDADE),
    CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ID_ESTADO)
        REFERENCES DIM_ESTADO(FK_DIM_ESTADO)
);

COMMENT ON TABLE DIM_CIDADE IS
    'Dimensão que armazena dados das cidades, referenciando o Estado ao qual pertence.';

COMMENT ON COLUMN DIM_CIDADE.FK_DIM_CIDADE IS
    'Chave primária gerada por IDENTITY para a dimensão CIDADE.';

COMMENT ON COLUMN DIM_CIDADE.NOME_CIDADE IS
    'Nome do município (por exemplo, São Paulo, Curitiba).';

COMMENT ON COLUMN DIM_CIDADE.NR_POPULACAO IS
    'População estimada da cidade.';

COMMENT ON COLUMN DIM_CIDADE.CODIGO_IBGE IS
    'Código da cidade segundo o IBGE.';

COMMENT ON COLUMN DIM_CIDADE.ALTITUDE IS
    'Altitude média da cidade em metros.';

COMMENT ON COLUMN DIM_CIDADE.ID_ESTADO IS
    'Chave estrangeira para DIM_ESTADO (Estado em que a cidade se encontra).';

-- =========================================================================
-- Tabela: DIM_BAIRRO
-- =========================================================================
CREATE TABLE DIM_BAIRRO (
    FK_DIM_BAIRRO       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOME_BAIRRO         VARCHAR2(100) NOT NULL,
    NR_POPULACAO_BAIRRO NUMBER(9,0),
    NR_NIVEL_SEGURANCA  NUMBER(1,0),
    ID_CIDADE           NUMBER        NOT NULL,
    CONSTRAINT PK_DIM_BAIRRO PRIMARY KEY (FK_DIM_BAIRRO),
    CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY (ID_CIDADE)
        REFERENCES DIM_CIDADE(FK_DIM_CIDADE)
);

COMMENT ON TABLE DIM_BAIRRO IS
    'Dimensão que detalha os bairros, vinculados a uma determinada cidade.';

COMMENT ON COLUMN DIM_BAIRRO.FK_DIM_BAIRRO IS
    'Chave primária gerada por IDENTITY para a dimensão BAIRRO.';

COMMENT ON COLUMN DIM_BAIRRO.NOME_BAIRRO IS
    'Nome do bairro (por exemplo, Bela Vista, Centro).';

COMMENT ON COLUMN DIM_BAIRRO.NR_POPULACAO_BAIRRO IS
    'População estimada do bairro.';

COMMENT ON COLUMN DIM_BAIRRO.NR_NIVEL_SEGURANCA IS
    'Índice ou indicador de segurança atribuído ao bairro, de 0 a 9 (exemplo).';

COMMENT ON COLUMN DIM_BAIRRO.ID_CIDADE IS
    'Chave estrangeira para DIM_CIDADE, indicando a cidade a que o bairro pertence.';

-- =========================================================================
-- Tabela: DIM_LOGRADOURO
-- =========================================================================
CREATE TABLE DIM_LOGRADOURO (
    FK_DIM_LOGRADOURO  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOME_LOGRADOURO    VARCHAR2(100),
    NR_LOGRADOURO      VARCHAR2(10),
    NR_CEP             VARCHAR2(15),
    ID_BAIRRO          NUMBER        NOT NULL,
    CONSTRAINT PK_DIM_LOGRADOURO PRIMARY KEY (FK_DIM_LOGRADOURO),
    CONSTRAINT FK_LOGRADOURO_BAIRRO FOREIGN KEY (ID_BAIRRO)
        REFERENCES DIM_BAIRRO(FK_DIM_BAIRRO)
);

COMMENT ON TABLE DIM_LOGRADOURO IS
    'Dimensão que armazena informações dos logradouros (rua, CEP, número etc.).';

COMMENT ON COLUMN DIM_LOGRADOURO.FK_DIM_LOGRADOURO IS
    'Chave primária gerada por IDENTITY para a dimensão LOGRADOURO.';

COMMENT ON COLUMN DIM_LOGRADOURO.NOME_LOGRADOURO IS
    'Nome da rua/avenida/travessa, etc. (ex.: Av. Paulista).';

COMMENT ON COLUMN DIM_LOGRADOURO.NR_LOGRADOURO IS
    'Número do endereço do logradouro (ex.: 100, 123B, S/N).';

COMMENT ON COLUMN DIM_LOGRADOURO.NR_CEP IS
    'CEP (Código de Endereçamento Postal).';

COMMENT ON COLUMN DIM_LOGRADOURO.ID_BAIRRO IS
    'Chave estrangeira para DIM_BAIRRO, indicando o bairro ao qual este logradouro pertence.';

-- =========================================================================
-- Tabela: DIM_CATEGORIA
-- =========================================================================
CREATE TABLE DIM_CATEGORIA (
    FK_DIM_CATEGORIA           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOME_CATEGORIA             VARCHAR2(100) NOT NULL,
    ST_CATEGORIA               CHAR(1)       NOT NULL,
    NR_AVALIACAO_CATEGORIA     NUMBER(3,1),
    CONSTRAINT PK_DIM_CATEGORIA PRIMARY KEY (FK_DIM_CATEGORIA)
);

COMMENT ON TABLE DIM_CATEGORIA IS
    'Dimensão que armazena as diferentes categorias de produtos.';

COMMENT ON COLUMN DIM_CATEGORIA.FK_DIM_CATEGORIA IS
    'Chave primária gerada por IDENTITY para a dimensão CATEGORIA.';

COMMENT ON COLUMN DIM_CATEGORIA.NOME_CATEGORIA IS
    'Nome da categoria (ex.: Eletrônicos, Eletrodomésticos).';

COMMENT ON COLUMN DIM_CATEGORIA.ST_CATEGORIA IS
    'Status da categoria (A=Ativa, I=Inativa).';

COMMENT ON COLUMN DIM_CATEGORIA.NR_AVALIACAO_CATEGORIA IS
    'Nota de avaliação média da categoria.';

-- =========================================================================
-- Tabela: DIM_SUBCATEGORIA
-- =========================================================================
CREATE TABLE DIM_SUBCATEGORIA (
    FK_DIM_SUBCATEGORIA        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOME_SUBCATEGORIA          VARCHAR2(100) NOT NULL,
    ST_SUB_CATEGORIA           CHAR(1)       NOT NULL,
    NR_AVALIACAO_SUB_CATEGORIA NUMBER(3,1),
    ID_CATEGORIA               NUMBER        NOT NULL,
    CONSTRAINT PK_DIM_SUBCATEGORIA PRIMARY KEY (FK_DIM_SUBCATEGORIA),
    CONSTRAINT FK_SUBCATEGORIA_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
        REFERENCES DIM_CATEGORIA(FK_DIM_CATEGORIA)
);

COMMENT ON TABLE DIM_SUBCATEGORIA IS
    'Dimensão que armazena as subcategorias de produtos, vinculadas a uma categoria maior.';

COMMENT ON COLUMN DIM_SUBCATEGORIA.FK_DIM_SUBCATEGORIA IS
    'Chave primária gerada por IDENTITY para a dimensão SUBCATEGORIA.';

COMMENT ON COLUMN DIM_SUBCATEGORIA.NOME_SUBCATEGORIA IS
    'Nome da subcategoria (ex.: Smartphones, Geladeiras).';

COMMENT ON COLUMN DIM_SUBCATEGORIA.ST_SUB_CATEGORIA IS
    'Status da subcategoria (A=Ativa, I=Inativa).';

COMMENT ON COLUMN DIM_SUBCATEGORIA.NR_AVALIACAO_SUB_CATEGORIA IS
    'Nota de avaliação média da subcategoria.';

COMMENT ON COLUMN DIM_SUBCATEGORIA.ID_CATEGORIA IS
    'Chave estrangeira para DIM_CATEGORIA, indicando a qual categoria pertence.';

-- =========================================================================
-- Tabela: DIM_PRODUTO
-- =========================================================================
CREATE TABLE DIM_PRODUTO (
    FK_DIM_PRODUTO  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOME_PRODUTO    VARCHAR2(150) NOT NULL,
    EMBALAGEM       VARCHAR2(50),
    ID_SUBCATEGORIA NUMBER        NOT NULL,
    CONSTRAINT PK_DIM_PRODUTO PRIMARY KEY (FK_DIM_PRODUTO),
    CONSTRAINT FK_PRODUTO_SUBCATEGORIA FOREIGN KEY (ID_SUBCATEGORIA)
        REFERENCES DIM_SUBCATEGORIA(FK_DIM_SUBCATEGORIA)
);

COMMENT ON TABLE DIM_PRODUTO IS
    'Dimensão que armazena informações detalhadas de cada produto.';

COMMENT ON COLUMN DIM_PRODUTO.FK_DIM_PRODUTO IS
    'Chave primária gerada por IDENTITY para a dimensão PRODUTO.';

COMMENT ON COLUMN DIM_PRODUTO.NOME_PRODUTO IS
    'Nome do produto (ex.: iPhone 14, TV 50 polegadas).';

COMMENT ON COLUMN DIM_PRODUTO.EMBALAGEM IS
    'Tipo de embalagem, se houver (ex.: caixa, envelope etc.).';

COMMENT ON COLUMN DIM_PRODUTO.ID_SUBCATEGORIA IS
    'Chave estrangeira para DIM_SUBCATEGORIA, definindo a subcategoria deste produto.';

-- =========================================================================
-- Tabela: DIM_CLIENTE
-- =========================================================================
CREATE TABLE DIM_CLIENTE (
    FK_DIM_CLIENTE      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NR_CLIENTE          NUMBER         NOT NULL,
    NOME_CLIENTE        VARCHAR2(100)  NOT NULL,
    NR_ESTRELAS         NUMBER(1,0),
    ST_CLIENTE          CHAR(1),
    DT_NASCIMENTO       DATE,
    ID_LOGRADOURO       NUMBER         NOT NULL,
    CONSTRAINT PK_DIM_CLIENTE PRIMARY KEY (FK_DIM_CLIENTE),
    CONSTRAINT FK_CLIENTE_LOGRADOURO FOREIGN KEY (ID_LOGRADOURO)
        REFERENCES DIM_LOGRADOURO(FK_DIM_LOGRADOURO)
);

COMMENT ON TABLE DIM_CLIENTE IS
    'Dimensão que armazena dados do cliente, vinculando o endereço via DIM_LOGRADOURO.';

COMMENT ON COLUMN DIM_CLIENTE.FK_DIM_CLIENTE IS
    'Chave primária gerada por IDENTITY para a dimensão CLIENTE.';

COMMENT ON COLUMN DIM_CLIENTE.NR_CLIENTE IS
    'Código de identificação do cliente no e-commerce.';

COMMENT ON COLUMN DIM_CLIENTE.NOME_CLIENTE IS
    'Nome completo do cliente.';

COMMENT ON COLUMN DIM_CLIENTE.NR_ESTRELAS IS
    'Nível de fidelidade ou pontuação do cliente (ex.: 3 estrelas de 5).';

COMMENT ON COLUMN DIM_CLIENTE.ST_CLIENTE IS
    'Status do cliente (A=Ativo, I=Inativo).';

COMMENT ON COLUMN DIM_CLIENTE.DT_NASCIMENTO IS
    'Data de nascimento do cliente (se disponível).';

COMMENT ON COLUMN DIM_CLIENTE.ID_LOGRADOURO IS
    'Chave estrangeira para DIM_LOGRADOURO, indicando o endereço do cliente.';

-- =========================================================================
-- Tabela: DIM_CENTRO_DISTRIBUICAO
-- =========================================================================
CREATE TABLE DIM_CENTRO_DISTRIBUICAO (
    FK_DIM_CENTRO_DISTRIBUICAO  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CD_CD                       NUMBER        NOT NULL,
    NOME_CENTRO_DISTRIBUICAO    VARCHAR2(100) NOT NULL,
    ID_LOGRADOURO               NUMBER        NOT NULL,
    CONSTRAINT PK_DIM_CENTRODIST PRIMARY KEY (FK_DIM_CENTRO_DISTRIBUICAO),
    CONSTRAINT FK_CENTRODIST_LOGRADOURO FOREIGN KEY (ID_LOGRADOURO)
        REFERENCES DIM_LOGRADOURO(FK_DIM_LOGRADOURO)
);

COMMENT ON TABLE DIM_CENTRO_DISTRIBUICAO IS
    'Dimensão que armazena dados de cada Centro de Distribuição (CD), incluindo endereço via DIM_LOGRADOURO.';

COMMENT ON COLUMN DIM_CENTRO_DISTRIBUICAO.FK_DIM_CENTRO_DISTRIBUICAO IS
    'Chave primária gerada por IDENTITY para a dimensão CENTRO DE DISTRIBUIÇÃO.';

COMMENT ON COLUMN DIM_CENTRO_DISTRIBUICAO.CD_CD IS
    'Código identificador do Centro de Distribuição no sistema (CD).';

COMMENT ON COLUMN DIM_CENTRO_DISTRIBUICAO.NOME_CENTRO_DISTRIBUICAO IS
    'Nome do Centro de Distribuição (ex.: CD Norte, CD SP-1).';

COMMENT ON COLUMN DIM_CENTRO_DISTRIBUICAO.ID_LOGRADOURO IS
    'Chave estrangeira para DIM_LOGRADOURO, indicando o endereço do CD.';

-- =========================================================================
-- Tabela: DIM_ENTREGADOR
-- =========================================================================
CREATE TABLE DIM_ENTREGADOR (
    FK_DIM_ENTREGADOR   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NOME_ENTREGADOR     VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_DIM_ENTREGADOR PRIMARY KEY (FK_DIM_ENTREGADOR)
);

COMMENT ON TABLE DIM_ENTREGADOR IS
    'Dimensão que armazena dados de cada entregador (pessoa responsável pelo transporte).';

COMMENT ON COLUMN DIM_ENTREGADOR.FK_DIM_ENTREGADOR IS
    'Chave primária gerada por IDENTITY para a dimensão ENTREGADOR.';

COMMENT ON COLUMN DIM_ENTREGADOR.NOME_ENTREGADOR IS
    'Nome do entregador ou profissional responsável pelo envio.';

-- =========================================================================
-- Tabela: DIM_DATA
-- =========================================================================
CREATE TABLE DIM_DATA (
    FK_DIM_DATA     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    DATA_COMPLETA   DATE          NOT NULL,
    ANO             NUMBER(4,0)   NOT NULL,
    MES             NUMBER(2,0)   NOT NULL,
    NOME_MES        VARCHAR2(20),
    DIA             NUMBER(2,0)   NOT NULL,
    NOME_DIA_SEMANA VARCHAR2(20),
    CONSTRAINT PK_DIM_DATA PRIMARY KEY (FK_DIM_DATA)
);

COMMENT ON TABLE DIM_DATA IS
    'Dimensão que armazena detalhes de datas, utilizada como Role-Playing (pedido, previsto, entrega).';

COMMENT ON COLUMN DIM_DATA.FK_DIM_DATA IS
    'Chave primária gerada por IDENTITY para a dimensão DATA.';

COMMENT ON COLUMN DIM_DATA.DATA_COMPLETA IS
    'Campo que armazena o dia exato no formato DATE (inclui hora, min, seg se necessário).';

COMMENT ON COLUMN DIM_DATA.ANO IS
    'Ano (yyyy).';

COMMENT ON COLUMN DIM_DATA.MES IS
    'Mês numérico (1 a 12).';

COMMENT ON COLUMN DIM_DATA.NOME_MES IS
    'Nome do mês (Janeiro, Fevereiro etc.).';

COMMENT ON COLUMN DIM_DATA.DIA IS
    'Dia numérico (1 a 31).';

COMMENT ON COLUMN DIM_DATA.NOME_DIA_SEMANA IS
    'Nome do dia da semana (segunda, terça etc.).';

-- =========================================================================
-- Tabela Fato: FATO_ENTREGA
-- =========================================================================
CREATE TABLE FATO_ENTREGA (
    FK_FATO_ENTREGA_PEDIDO   NUMBER  NOT NULL,
    FK_FATO_ENTREGA_ITEM     NUMBER  NOT NULL,
    -- Chaves estrangeiras
    ID_CLIENTE               NUMBER  NOT NULL,  -- DIM_CLIENTE
    ID_PRODUTO               NUMBER  NOT NULL,  -- DIM_PRODUTO
    ID_CENTRO_DIST           NUMBER  NOT NULL,  -- DIM_CENTRO_DISTRIBUICAO
    ID_ENTREGADOR            NUMBER,            -- DIM_ENTREGADOR
    ID_DATA_PEDIDO           NUMBER  NOT NULL,  -- DIM_DATA
    ID_DATA_PREVISTA         NUMBER  NOT NULL,  -- DIM_DATA
    ID_DATA_ENTREGA          NUMBER  NOT NULL,  -- DIM_DATA
    -- Medidas
    QUANTIDADE               NUMBER(10,0) NOT NULL,
    QT_PROD_ENTREGUE         NUMBER(10,0) NOT NULL,
    VL_UNITARIO              NUMBER(12,2) NOT NULL,
    VL_TOTAL                 NUMBER(12,2) NOT NULL,
    PERC_ICMS                NUMBER(5,2),
    NOTA_EMBALAGEM           NUMBER(2,0),
    NOTA_PONTUALIDADE        NUMBER(2,0),
    NOTA_CORTESIA            NUMBER(2,0),
    TEMPO_ENTREGA_MIN        NUMBER(10,0),
    -- PK
    CONSTRAINT PK_FATO_ENTREGA PRIMARY KEY 
        (FK_FATO_ENTREGA_PEDIDO, FK_FATO_ENTREGA_ITEM),
    -- FKs
    CONSTRAINT FK_FATO_CLIENTE FOREIGN KEY (ID_CLIENTE)
        REFERENCES DIM_CLIENTE(FK_DIM_CLIENTE),
    CONSTRAINT FK_FATO_PRODUTO FOREIGN KEY (ID_PRODUTO)
        REFERENCES DIM_PRODUTO(FK_DIM_PRODUTO),
    CONSTRAINT FK_FATO_CENTRO FOREIGN KEY (ID_CENTRO_DIST)
        REFERENCES DIM_CENTRO_DISTRIBUICAO(FK_DIM_CENTRO_DISTRIBUICAO),
    CONSTRAINT FK_FATO_ENTREGADOR FOREIGN KEY (ID_ENTREGADOR)
        REFERENCES DIM_ENTREGADOR(FK_DIM_ENTREGADOR),
    CONSTRAINT FK_FATO_DATA_PED FOREIGN KEY (ID_DATA_PEDIDO)
        REFERENCES DIM_DATA(FK_DIM_DATA),
    CONSTRAINT FK_FATO_DATA_PREV FOREIGN KEY (ID_DATA_PREVISTA)
        REFERENCES DIM_DATA(FK_DIM_DATA),
    CONSTRAINT FK_FATO_DATA_ENT FOREIGN KEY (ID_DATA_ENTREGA)
        REFERENCES DIM_DATA(FK_DIM_DATA)
);

COMMENT ON TABLE FATO_ENTREGA IS
    'Tabela Fato (grão: Pedido + Item). Armazena medições de entrega, ligando-se às dimensões Cliente, Produto, CD, Entregador e Datas.';

COMMENT ON COLUMN FATO_ENTREGA.FK_FATO_ENTREGA_PEDIDO IS
    'Número do pedido (código natural do sistema transacional). Parte 1 da PK.';

COMMENT ON COLUMN FATO_ENTREGA.FK_FATO_ENTREGA_ITEM IS
    'Número sequencial do item dentro do pedido. Parte 2 da PK.';

COMMENT ON COLUMN FATO_ENTREGA.ID_CLIENTE IS
    'FK para DIM_CLIENTE (quem recebe o produto).';

COMMENT ON COLUMN FATO_ENTREGA.ID_PRODUTO IS
    'FK para DIM_PRODUTO (qual produto foi comprado).';

COMMENT ON COLUMN FATO_ENTREGA.ID_CENTRO_DIST IS
    'FK para DIM_CENTRO_DISTRIBUICAO (qual CD despachou o produto).';

COMMENT ON COLUMN FATO_ENTREGA.ID_ENTREGADOR IS
    'FK para DIM_ENTREGADOR (profissional que realizou a entrega).';

COMMENT ON COLUMN FATO_ENTREGA.ID_DATA_PEDIDO IS
    'FK para DIM_DATA, indicando a data/hora em que o pedido foi criado.';
    
COMMENT ON COLUMN FATO_ENTREGA.ID_DATA_PREVISTA IS
    'FK para DIM_DATA, indicando a data/hora prevista de entrega ao cliente.';

COMMENT ON COLUMN FATO_ENTREGA.ID_DATA_ENTREGA IS
    'FK para DIM_DATA, indicando a data/hora real de entrega ao cliente.';

COMMENT ON COLUMN FATO_ENTREGA.QUANTIDADE IS
    'Quantidade de itens solicitados no pedido.';

COMMENT ON COLUMN FATO_ENTREGA.QT_PROD_ENTREGUE IS
    'Quantidade efetiva de itens que foram entregues (pode variar da quantidade pedida).';

COMMENT ON COLUMN FATO_ENTREGA.VL_UNITARIO IS
    'Valor unitário do item no momento da compra.';

COMMENT ON COLUMN FATO_ENTREGA.VL_TOTAL IS
    'Valor total da linha, normalmente QUANTIDADE x VL_UNITARIO.';

COMMENT ON COLUMN FATO_ENTREGA.PERC_ICMS IS
    'Percentual de ICMS aplicado ao produto neste pedido.';

COMMENT ON COLUMN FATO_ENTREGA.NOTA_EMBALAGEM IS
    'Avaliação (0 a 10) do cliente quanto à embalagem do produto.';

COMMENT ON COLUMN FATO_ENTREGA.NOTA_PONTUALIDADE IS
    'Avaliação (0 a 10) do cliente quanto à pontualidade (cumprimento do prazo).';

COMMENT ON COLUMN FATO_ENTREGA.NOTA_CORTESIA IS
    'Avaliação (0 a 10) do cliente quanto à cordialidade do entregador.';

COMMENT ON COLUMN FATO_ENTREGA.TEMPO_ENTREGA_MIN IS
    'Tempo total de entrega em minutos, calculado entre pedido e entrega real.';