SELECT 
    cdc.NOME_CENTRO_DISTRIBUICAO AS cd_nome,
    ROUND(AVG(f.TEMPO_ENTREGA_MIN), 2) AS media_tempo_entrega
FROM FATO_ENTREGA f
JOIN DIM_CENTRO_DISTRIBUICAO cdc 
    ON f.SK_CENTRO_DISTRIBUICAO = cdc.SK_CENTRO_DISTRIBUICAO
GROUP BY 
    cdc.NOME_CENTRO_DISTRIBUICAO
ORDER BY 
    media_tempo_entrega;